### PR TITLE
[9.3/bugfixes] Fixed DELL API to V5

### LINKED ISSUE #79: Dell API - V5
Hi!
Dell changes their API procedures to get warranty status. They are using V5 now.
Somebody knows how to fix it?

### PR DESCRIPTION
**Pull request by tomolimo**
Set version to 2.1.3
fixes #79

### CODE REVIEW

**Comment by Langelot007** [comment]
Super merci ! :)

**Comment by pablitobin** [comment]
Works for 9.4.3? I have this error:
image

**Comment by tomolimo** [comment]
For GLPI 9.4.3 you need the 2.2.1 release as quoted here https://github.com/InfotelGLPI/manufacturersimports/issues/79#issuecomment-574116025

**Comment by tomolimo** [comment]
Revert $supplierSecret deleted line
Set version to 2.1.4
fixes #82 (comment)

**Comment by samianiba** [comment]
Hello, i have introduced the API Keys for DELL, but everytime it try to import the warranty information i have the message : Import KO , can you help about that ? Thanks 
image

**Comment by tomolimo** [comment]
Hello @samianiba 
If you have an issue, you must post a new issue in the issue list, and not in a pull request...
https://github.com/InfotelGLPI/manufacturersimports/issues
Thank you,
Regards,
Tomolimo

**Pull request closed without merging**
