### PR TITLE
Changing Lenovo URL

### PR DESCRIPTION
**Pull request by WooboyTW**
Change lenovo warranty status query URL

### CODE REVIEW

**Comment by amma35** [comment]
What is the url you get in the link?
I get "http://www3.lenovo.com/us/en/warranty/*****?machineType=" 
and this error: "{" errorType ":" 2 "," errorMsg ":" Messages of HybrisWarrantyInfo is empty. "}"

**Comment by WooboyTW** [comment]
you need a valid Lenovo PC serial number

An example from lenovo offical web site
query from this URL: http://www3.lenovo.com/us/en/warranty-upgrades?serial-number=23AB123

it actual get the detail with AJAX query URL: http://www3.lenovo.com/us/en/warranty/23AB123?machineType=
and return json

if you use invalid serial number
it's only return error

**Comment by Tomiliy** [comment]
what do you mean?
where can i change the query Url and how?
and in what should i change the Query URL?
Thanks

**Comment by amma35** [comment]
Yes of course I have entered a good serial number but with the code entered in the variable supplier_url I can not get to the correct url.

Several points need to be revisited:
- The indentation of the code is not good
- the variable supplier_url is used to create the configuration of the manufacturer so you must enter the url used to retrieve the information of the guarantees
- You must modify in the file hook.php to modify the new url
- And see the modification requested in the review

**Comment by WooboyTW** [comment]
OK, I understand
I'll create new pull request after fix the code

thanks your suggestion.

**Comment by Tomiliy** [comment]
Thank you...

**Comment by amma35** [comment]
You can modify this branch

**Comment by WooboyTW** [comment]
@amma35 
I found some problem in query,
I thought it could be the same problem with you
can you help me test with your serial number?

I have test the plugin after modify with our company PCs, 
almost of all PC can retrieve the warranty date
only 2 or 3 old PC cannot get data without machineType parameter
  e.g. http://www3.lenovo.com/us/en/warranty/L3ABY3X?machineType=
It's work fine with type number (the first 4 letters or numbers of model number)
  e.g. http://www3.lenovo.com/us/en/warranty/L3ABY3X?machineType=7298

even on purchase warranty upgrade site, it can't find warranty information either
http://www3.lenovo.com/us/en/warranty-upgrades?serial-number=L3ABY3X

maybe it's Lenovo db query bug

**Comment by Tomiliy** [comment]
manually this site is working: http://www3.lenovo.com/us/en/warranty-upgrades?serial-number=xxxxxx
Can you build a working scenario on it?

**Comment by amma35** [comment]
Commit https://github.com/InfotelGLPI/manufacturersimports/commit/e28781743e001d87e2e2cdb308cd68e67d51eeb7

**Pull request closed without merging**
