### PR TITLE
[GLPI 9.4] Fixed DELL API to V5

### LINKED ISSUE #79: Dell API - V5
Hi!
Dell changes their API procedures to get warranty status. They are using V5 now.
Somebody knows how to fix it?

### PR DESCRIPTION
**Pull request by tomolimo**
Set version to 2.2.1
GLPI 9.4
fixes #79

### CODE REVIEW

**Comment by LDanton95** [comment]
Great !!! It work !
Thanks a lot Tomolimo :-)

Ludo.

**Comment by tomolimo** [comment]
you're welcome
😃

**Comment by lubyou** [comment]
Hi,

It seems to work, I get the notice below in my log file though:
```
[2020-01-14 17:59:12] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi.vnci.io/9.4.5/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined variable: supplierSecret
  Backtrace :
  ...nufacturersimports/inc/postimport.class.php:411
  ...nufacturersimports/inc/postimport.class.php:213 PluginManufacturersimportsPostImport::seePostImport()
  .../manufacturersimports/ajax/massiveaction.php:48 PluginManufacturersimportsPostImport::massiveimport()
  {"user":"10@de","mem_usage":"0.000\", 3.06Mio)"}
```

Thanks

**Comment by tomolimo** [comment]
Hello,
I'll check that tomorrow. 
Thank you for your report. 
Regards 
Tomolimo

**Comment by tomolimo** [comment]
Revert $supplierSecret deleted line
Set version to 2.2.2
fixes https://github.com/InfotelGLPI/manufacturersimports/pull/82#issuecomment-574273446

**Comment by abpetit** [comment]
Great ! It works, thank you

**Comment by tcapacci** [comment]
How  do I add the correction, do I have to wait for the plugin update to be released?

**Comment by tomolimo** [comment]
Hello
You may use the files from master branch from my fork. Or use the files from the commit itself. 
Copy them over your existing folder (of course backup everything before, like any other plugin upgrade) . 
It will behave like an upgrade.
Regards 
Tomolimo

**Comment by tcapacci** [comment]
Thank you.

I have now the 2.2.2 version listed (GLPI 9.4)...

maybe unrelated but i have added the Dell supplier in the plugin settings and I keep getting the belwo message when tryng to use it: 

Choose inventory type and manufacturer
--
No manufacturer available. Please configure at least one manufacturer

**Comment by keha35** [comment]
Hi,

First thanks for this update!
I accept this PR and will create a new release after some code lisibility updates.

BR.

**Review by Asif198788 — COMMENTED** [review]
H

**Pull request merged**
